name: Build (frps)

on:
  schedule:
    - cron: '0 19 * * *'
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: linux/amd64
            label: amd64
          - platform: linux/arm64
            label: arm
    runs-on: [self-hosted, "${{ matrix.label }}"]

    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3

      - name: Log in to the Github Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/build-push-action@v4
        id: build
        with:
          context: .
          file: ./frps.Dockerfile
          platforms: ${{ matrix.platform }}
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/frps:${{ matrix.label }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  merge:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Log in to the Github Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Merge manifests
        working-directory: /tmp/digests
        run: |  # Check matrix.platform in build job
          docker manifest create ghcr.io/${{ github.repository_owner }}/frps:latest \
            ghcr.io/${{ github.repository_owner }}/frps:amd64 \
            ghcr.io/${{ github.repository_owner }}/frps:arm
          docker manifest push ghcr.io/${{ github.repository_owner }}/frps:latest

  mirror:
    runs-on: ubuntu-latest
    needs: merge
    steps:
      - name: Log in to the Github Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Login to Aliyun Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.ALIYUN_REGISTRY }}
          username: ${{ secrets.ALIYUN_USERNAME }}
          password: ${{ secrets.ALIYUN_PASSWORD }}
      
      - name: Push to Aliyun Container registry
        run: |
          docker pull ghcr.io/${{ github.repository_owner }}/frps:latest
          docker tag ghcr.io/${{ github.repository_owner }}/frps:latest ${{ secrets.ALIYUN_REGISTRY }}/${{ secrets.ALIYUN_NAMESPACE }}/frps:latest
          docker push ${{ secrets.ALIYUN_REGISTRY }}/${{ secrets.ALIYUN_NAMESPACE }}/frps:latest
